#!/usr/bin/env bash
# Script that will display information about subdomains.

function showDomains {
    SUBDOMAINS=("www" "lb-01" "web-01" "web-02")
    if [ -z "$2" ]
    then
      for element in "${!SUBDOMAINS[@]}"; do
          dig "${SUBDOMAINS[$element]}.$1" | grep -A1 "ANSWER SECTION:" | tail -n1 | awk '{split($0, SUBDOMAIN, "."); print "The subdomain " SUBDOMAIN[1] " is a " $4 " record and points to " $5}'
      done
    else
        dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tail -n1 | awk '{split($0, SUBDOMAIN, "."); print "The subdomain " SUBDOMAIN[1] " is a " $4 " record and points to " $5}'
    fi
}

showDomains "$1" "$2"