#!/usr/bin/env bash
#Set up nginx web server into 4521-web-01 server.
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www//html/index.html
