#!/usr/bin/env bash
#Set up nginx web server into 4521-web-01 server.
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
new_string="\\\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "19i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
