#!/usr/bin/env bash
# Script that prints Best School 10 times, but in 9th line prints hi.

var='Best School'
i=1
while [ "$i" -le 10 ];
do
    echo "$var"
    if [[ "$i" -eq 9 ]];
    then
        echo "hi"
    fi
    ((i++))
done
