#!/usr/bin/env bash
# Script that prints the numbers in an hour.

HOUR=0
while [ "$HOUR" -le 12 ]; do
    echo "Hour: $HOUR"
    MINUTE=1
    while [ "$MINUTE" -lt 60 ]; do
	echo "$MINUTE"
	((MINUTE++))
    done
    ((HOUR++))
done
