#!/usr/bin/env bash
# Script that prints file descriptions.

FILE=school

if [[ -f $FILE ]];
then
    echo "school file exists"
    if [[ -s $FILE ]]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    echo "school is a regular file"
else
    echo "school file does not exist"
fi